### ISSUE TITLE
Buttons / UITextField

### ISSUE THREAD

**Issue by JulesMoorhouse** [alexruperez/ARAlertController#1]
I was looking for a replacement for the uialertview with three buttons, ok, forgot and cancel, be nice to see a screenshot with more buttons and a uitextfield, maybe example code showing how to access the text value too.

**Comment by alexruperez** [comment]
@Jules2010 your wish is [granted](http://stevenarch.tymoon.eu/fab/src/132285338850.jpg)! Check out https://github.com/alexruperez/ARAlertController/commit/d1a794ac1bcc25ca2ba518d9c54d45e482c202f7
