### ISSUE TITLE
[alert addSubview:pickerView];

### ISSUE THREAD

**Issue by JulesMoorhouse** [alexruperez/ARAlertController#2]
It would be awesome if I could add views, like a picker to ARAlertController.

I've already decided to use this is another project, for the alert functionality.
Thought I'd try the action sheet stuff in another, however I couldn't addSubview.

Any workarounds ?

Thanks in advance

Jules.

**Comment by alexruperez** [comment]
Sadly not natively supported, to add subviews i recommend [wimagguc](https://github.com/wimagguc)/[ios-custom-alertview](https://github.com/wimagguc/ios-custom-alertview).

Thank you @Jules2010
